version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  unittest-test:
    docker:
      - image: cimg/node:16.10
    working_directory: ~/starknet-bridge-relayer/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run unit tests
          command: yarn test
  e2e-test:
    docker:
      - image: cimg/node:16.10
    working_directory: ~/starknet-bridge-relayer/e2e
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: build docker compose
          command: make e2e-build
      - run:
          name: start docker compose
          command: make e2e-up && sleep 10
      - run:
          name: start docker compose
          command: make e2e-setup && sleep 10
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - run:
          name: Run e2e tests
          command: make e2e-test
      - run:
          name: Stop containers
          command: make e2e-down

workflows:
  tests:
    jobs:
      - unittest-test
      - e2e-test:
          requires:
              - unittest-test
