version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  indexer:
    image: shardastronaut/stargate-bridge-indexer:latest
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL}
      MONGO_URL: mongodb://mongo:27017
      ETH_BRIDGE_ADDRESS: ${ETH_BRIDGE_ADDRESS}
      DAI_BRIDGE_ADDRESS: ${DAI_BRIDGE_ADDRESS}
      GRAPHQL_URL: ${GRAPHQL_URL}
      GRAPHQL_PORT: ${GRAPHQL_PORT}
      BUILD_ENV: ${BUILD_ENV}
      FIRST_BLOCK: ${FIRST_BLOCK}
      LOGLEVEL: ${LOG_LEVEL}
    ports:
      - 8080:8080
    depends_on:
      - mongo
    entrypoint: ['/bin/bash', '-c', 'poetry run indexer graphql-start']

  relayer-test:
    build:
      context: ..
      target: development
    restart: always
    environment:
      RELAYER_PORT: ${RELAYER_PORT}
      GRAPHQL_URL: ${GRAPHQL_URL}
      GRAPHQL_PORT: ${GRAPHQL_PORT}
      NETWORK_ID: ${NETWORK_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      MONGO_URL: ${MONGO_URL}
      MONGO_INITDB_NAME: ${MONGO_INITDB_NAME}
      INFURA_RPC_URL: ${INFURA_RPC_URL}
      ALCHEMY_RPC_URL: ${ALCHEMY_RPC_URL}
      FIRST_BLOCK: ${FIRST_BLOCK}
      INDEXER_URL: ${INDEXER_URL}
      NUMBER_OF_BLOCKS_TO_PROCESS_PER_CHUNK: ${NUMBER_OF_BLOCKS_TO_PROCESS_PER_CHUNK}
      MIN_TRANSACTIONS_TO_PROCESS: ${MIN_TRANSACTIONS_TO_PROCESS}
      RELAYER_L2_ADDRESS: ${RELAYER_L2_ADDRESS}
      RELAYER_SLEEP_AFTER_SUCCESS_EXEC: ${RELAYER_SLEEP_AFTER_SUCCESS_EXEC}
      RELAYER_SLEEP_AFTER_FAIL_EXEC: ${RELAYER_SLEEP_AFTER_FAIL_EXEC}
      TRUSTED_MODE: ${TRUSTED_MODE}
      RPC_URL: ${RPC_URL}
    command: ['/bin/bash', '-c', 'sleep 2000']
    depends_on:
      - mongo
      - hardhat
      - indexer

  hardhat:
    build:
      context: ./starknet-core
    restart: always
    environment:
      RPC_URL: ${RPC_URL}
      NETWORK_ID: ${NETWORK_ID}
    ports:
      - 8545:8545
    entrypoint: ['/bin/bash', '-c', 'scripts/start.sh']
