name: release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
      
      - name: Init Git user
        run: |
          git config --global user.email "127413534+shardAstronaut@users.noreply.github.com"
          git config --global user.name "shardAstronaut"

      - name: Release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}