name: release

on: workflow_dispatch
  # workflow_run:
  #   workflows:
  #     - tests
  #   branches:
  #     [main, simulation/e2e]
  #   types: 
  #     - completed
  

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
      
      - name: Release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Changelog
      #   id: github_release
      #   uses: mikepenz/release-changelog-builder-action@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   uses: mikepenz/action-gh-release@v0.2.0-a03
      #   with:
      #     body: ${{steps.github_release.outputs.changelog}}
